version: "3.8"

services:
  db:
    image: postgres:15
    container_name: meu_projeto_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: meu_banco
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: meu_projeto_app
    restart: always
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: user
      DB_PASS: password
      DB_NAME: meu_banco
    env_file:
      - ./backend/.env
    volumes:
      - .:/app
      - /app/node_modules
    command: ["node", "src/server.js"]

volumes:
  pgdata: